version: "3.3"
services: 

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # container_name: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boxflix

  webserver:
    image: nginx:alpine
    container_name: nomePrj-webserver
    working_dir: /usr/src/application
    volumes:
        - ./src:/usr/src/application
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"

  php-fpm:
    build: php-fpm
    container_name: nomePrj-php-fpm
    working_dir: /usr/src/application
    volumes:
      - ./src:/usr/src/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

